package de.fraunhofer.fit.train.model_v1;

import javax.xml.bind.annotation.XmlElement;

import org.bson.types.ObjectId;
import org.springframework.data.annotation.Id;

import com.google.gson.annotations.Expose;
import com.google.gson.annotations.SerializedName;

public class TrainAbstract {
	
	@Id
	private ObjectId _id;
	

	@SerializedName("name")
	@Expose
	private String name;

	@SerializedName("internalId")
	@Expose
	private String internalId;

	@SerializedName("internalVersion")
	@Expose
	private String internalVersion;

	@SerializedName("internalPointer")
	@Expose
	private String internalPointer;
	
	@SerializedName("correlationObjectId")
	@Expose
	private String correlationObjectId;
	
	@SerializedName("description")
	@Expose
	private String description;
	
	
	
	
	
	
	public String getCorrelationObjectId() {
		return this.get_id().toString();
	}


	public void setCorrelationObjectId(String correlationObjectId) {
		this.correlationObjectId = correlationObjectId;
	}


	public String getDescription() {
		return description;
	}


	public void setDescription(String description) {
		this.description = description;
	}


	public ObjectId get_id() {
		return _id;
	}


	public void set_id(ObjectId _id) {
		this._id = _id;
	}
	
	/**
	 * "Occurrence: 1 This field aims to hold an optional name for the wagon
	 * instance."
	 * 
	 * @author Joao Bosco Jares MSc. (Software Engineer)
	 * @see www.jbjares.com
	 * @see jbjares@gmail.com, joao.bosco.jares.alves.chaves@fit.fraunhofer.de
	 */
	public String getName() {
		return name;
	}

	/**
	 * "Occurrence: 1 This field aims to hold an optional name for the wagon
	 * instance."
	 * 
	 * @author Joao Bosco Jares MSc. (Software Engineer)
	 * @see www.jbjares.com
	 * @see jbjares@gmail.com, joao.bosco.jares.alves.chaves@fit.fraunhofer.de
	 */
	@XmlElement
	public void setName(String name) {
		this.name = name;
	}
	


	/**
	 * "Occurrence: 1 The internalId field is autogenerated by the Train DOI
	 * Repository profile. This field is important for the kernel, once it aims to
	 * be the holder of the internal identifier which is used to reforce the
	 * relations and linkage between the Wagon and other objects together the DOI or
	 * to mimic the DOI till could be retrieved."
	 * 
	 * @author Joao Bosco Jares MSc. (Software Engineer)
	 * @see www.jbjares.com
	 * @see jbjares@gmail.com, joao.bosco.jares.alves.chaves@fit.fraunhofer.de
	 *
	 */
	public String getInternalId() {
		return internalId;
	}

	/**
	 * "Occurrence: 1 The internalId field is autogenerated by the Train DOI
	 * Repository profile. This field is important for the kernel, once it aims to
	 * be the holder of the internal identifier which is used to reforce the
	 * relations and linkage between the Wagon and other objects together the DOI or
	 * to mimic the DOI till could be retrieved."
	 * 
	 * @author Joao Bosco Jares MSc. (Software Engineer)
	 * @see www.jbjares.com
	 * @see jbjares@gmail.com, joao.bosco.jares.alves.chaves@fit.fraunhofer.de
	 *
	 */
	@XmlElement
	public void setInternalId(String internalId) {
		this.internalId = internalId;
	}

	/**
	 * "Occurrence: 1 The internalVersion field is autogenerated by the Train DOI
	 * Repository profile. This field is important for the kernel, once it aims to
	 * be the holder of the internal version. This field is useful to validade and
	 * correlate versions from different instances or organizations."
	 * 
	 * @author Joao Bosco Jares MSc. (Software Engineer)
	 * @see www.jbjares.com
	 * @see jbjares@gmail.com, joao.bosco.jares.alves.chaves@fit.fraunhofer.de
	 *
	 */
	public String getInternalVersion() {
		return internalVersion;
	}

	/**
	 * "Occurrence: 1 The internalVersion field is autogenerated by the Train DOI
	 * Repository profile. This field is important for the kernel, once it aims to
	 * be the holder of the internal version. This field is useful to validade and
	 * correlate versions from different instances or organizations."
	 * 
	 * @author Joao Bosco Jares MSc. (Software Engineer)
	 * @see www.jbjares.com
	 * @see jbjares@gmail.com, joao.bosco.jares.alves.chaves@fit.fraunhofer.de
	 *
	 */
	@XmlElement
	public void setInternalVersion(String internalVersion) {
		this.internalVersion = internalVersion;
	}

	/**
	 * "Occurrence: 1 The Train internal pointer is an field which aims to hold the
	 * ""composed key"" defined by the internalId, internalVersion and
	 * sourceRepository. This field is used to facilitate the navigation between
	 * Trains distributed along of heterogeneous repositories or Handles. This
	 * attribute could be used as an URL rewriting parameter to find a specific
	 * train as well as his resources/files under the webdav, once for each new
	 * train a new folder on the webdav should be created, named by the
	 * internalPointer, which is a way of desanbiguation, not just for the Train,
	 * but for his dependencies (resources/files which are part of a single model) "
	 * 
	 * @author Joao Bosco Jares MSc. (Software Engineer)
	 * @see www.jbjares.com
	 * @see jbjares@gmail.com, joao.bosco.jares.alves.chaves@fit.fraunhofer.de
	 *
	 */
	public String getInternalPointer() {
		return internalPointer;
	}

	/**
	 * "Occurrence: 1 The Train internal pointer is an field which aims to hold the
	 * ""composed key"" defined by the internalId, internalVersion and
	 * sourceRepository. This field is used to facilitate the navigation between
	 * Trains distributed along of heterogeneous repositories or Handles. This
	 * attribute could be used as an URL rewriting parameter to find a specific
	 * train as well as his resources/files under the webdav, once for each new
	 * train a new folder on the webdav should be created, named by the
	 * internalPointer, which is a way of desanbiguation, not just for the Train,
	 * but for his dependencies (resources/files which are part of a single model) "
	 * 
	 * @author Joao Bosco Jares MSc. (Software Engineer)
	 * @see www.jbjares.com
	 * @see jbjares@gmail.com, joao.bosco.jares.alves.chaves@fit.fraunhofer.de
	 *
	 */
	@XmlElement
	public void setInternalPointer(String internalPointer) {
		this.internalPointer = internalPointer;
	}
	
	
//	@SerializedName("correlationObjectId")
//	@Expose
//	private String correlationObjectId;
//	
//	
//
//
//
//	public String getCorrelationObjectId() {
//		if(!"".equals(this.correlationObjectId)) {
//			return this.correlationObjectId;
//		}
//		
//		if(this._id!=null && this._id.get()!=null && this._id.get().toString()!=null && !"".equals(this._id.get().toString()) ) {
//			return this._id.get().toString();
//		}
//		throw new RuntimeException("Fail to obtain the field correlationObjectId from TrainAbstract!");
//	}
//
//	public void setCorrelationObjectId(String correlationObjectId) {
//		this.correlationObjectId = correlationObjectId;
//	}


}
