version: '3'

services:
# DB  ***************************************************************************************
  mongo:
    image: jbjares/mongo_java8_maven:v1
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/db.log
    volumes:
      - ./data/db:/data/db
    ports:
        - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null # --quiet
    
    # mongod 0.0.0.0 --port 27017

    # sudo docker run -d -p 27017:27017 jbjares/mongo_java8_maven:v1 mongod --bind_ip_all --ipv6 --port 27017
    
    
    
    