package de.fraunhofer.fit.train.persistence;

import java.util.List;

import org.springframework.data.mongodb.repository.Query;
import org.springframework.data.repository.CrudRepository;
import org.springframework.data.repository.query.QueryByExampleExecutor;

import de.fraunhofer.fit.train.model_v2.autogenerated.InternalPointer;

public interface IInternalPointerRepository extends CrudRepository<InternalPointer, String>, QueryByExampleExecutor<InternalPointer> {

	@Query("{ '?0' : { $regex: ?1 } }")
	List<InternalPointer> findOneByQuery(String fieldStr,String cotent);

	@Query("{ ?0 : { $regex: ?1 } }")
	List<InternalPointer> findOneBySmampleQuery(String fieldStr,String cotent);
	
	@Query(value="{}", fields="{ '0' : ?1}")
	List<InternalPointer> findOneBySimpleQuery(String fieldStr,String cotent);

	@Query("{ ?0 : { $regex: ?1 } }")
	List<InternalPointer> findOneByRegexQuery(String fieldStr, String cotent);
	
	
}