package de.fraunhofer.fit.train.model_v2.autogenerated;

import org.bson.types.ObjectId;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;
import org.springframework.stereotype.Repository;


@Repository
@Document(collection = "internalId")
public class InternalId {
	
	@Id
	private ObjectId _id;

	public ObjectId get_id() {
		return _id;
	}

	public void set_id(ObjectId _id) {
		this._id = _id;
	}
	
	

}
